version: "0.2"
services:
  nginx:
    container_name: nginx
    image: andarius/nginx-upload
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/certs
      - ./data/nginx/tmp:/tmp
      - ./data/attachments:/attachments
    ports:
      - "80:80"
      - "443:443"
      - "5050:5050"
    depends_on:
      - backend
      - celery-flower
      - cloudbeaver
  #    command: [ nginx-debug, '-g', 'daemon off;' ]  # uncomment to enable debug mode


  backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV:-development}
    command: ./start-backend.sh
    volumes:
      - ./data/nginx/tmp:/tmp
      - ./data/attachments:/attachments
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    container_name: flutter-web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV:-development}
#    command: flutter run -d web-server --web-port=80
    env_file:
      - .env
    ports:
      - "1200:80"

  db:
      container_name: oracle-db
      hostname: oracle-db
      shm_size: 8g  
      ports:
          - '1521:1521'
      volumes:
          - oracle-data:/opt/oracle/oradata
          - oracle-backup:/opt/oracle/backup
      image: container-registry.oracle.com/database/free
      env_file:
        - .env
      environment:
        ORACLE_PWD: $ORACLE_ADMIN_PASSWORD
        ORACLE_ALLOW_REMOTE: true
        ORACLE_SID: $ORACLE_SID

  cloudbeaver:
      container_name: cloudbeaver
      build:
        context: ./cloudbeaver
        dockerfile: Dockerfile
      ports:
       - '8080:8978'
      env_file:
       - .env
      environment:
        CB_SERVER_NAME: "Test Cloudbeaver instance"
        CB_SERVER_URL: "http://localhost:8978"
        CB_ADMIN_NAME: $CLOUDBEAVER_ADMIN_USERNAME
        CB_ADMIN_PASSWORD: $CLOUDBEAVER_ADMIN_PASSWORD
      volumes: 
       - ./data/cloudbeaver:/opt/cloudbeaver/workspace
      depends_on:
        - db

  celery-worker:
    container_name: celery-worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./start-worker.sh
    volumes:
      - ./data/attachments:/attachments
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    container_name: celery-beat
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./start-beat.sh
    volumes:
      - ./data/attachments:/attachments
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-flower:
    container_name: celery-flower
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./start-flower.sh
    env_file:
      - .env
    environment:
      - FLOWER_URL_PREFIX=flower
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

  redis:
    container_name: "redis"
    image: redis:7.2-alpine
    # ports:
    #   - 6379:6379

volumes:
  oracle-data:
  oracle-backup:
