name: mypy

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        cd backend
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Run mypy analysis
      run: |
        cd backend/app
        poetry shell
        mypy .
