name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Oracle container image registry
      uses: docker/login-action@v3
      with:
        registry: container-registry.oracle.com
        username: ${{ secrets.ORACLE_REGISTRY_USERNAME }}
        password: ${{ secrets.ORACLE_REGISTRY_PASSWORD }}
    - name: Set up envfile
      run: |
        - cp .env.sample .env
    - name: Build container images
      run: |
        docker compose build --build-arg "BUILD_ENV=test"
    - name: Run containers in detached mode
      run: |
        docker compose up --detach
    - name: Wait for startup   # todo not too elegant
      run: |
        sleep 30
    - name: Run pytest
      run: |
        docker exec fastapi-backend "pytest"
